name: pokedex
description: A pokedex project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:


  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1


  dio: ^4.0.4

  flutter_hooks: ^0.18.2+1

  cupertino_icons: ^1.0.2

  equatable: ^2.0.3

  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family:  PokemonHollow
      fonts:
        - asset: assets/fonts/PokemonHollow.ttf
    - family:  PokemonSolid
      fonts:
        - asset: assets/fonts/PokemonSolid.ttf   

  assets:
    - assets/
